export const defaultImages = [
  {
    id: "78B_asQgBJ4",
    slug: "brown-rocky-mountain-under-starry-night-78B_asQgBJ4",
    alternative_slugs: {
      en: "brown-rocky-mountain-under-starry-night-78B_asQgBJ4",
      es: "montana-rocosa-marron-bajo-la-noche-estrellada-78B_asQgBJ4",
      ja: "星降る夜の下の茶色の岩山-78B_asQgBJ4",
      fr: "montagne-rocheuse-brune-sous-la-nuit-etoilee-78B_asQgBJ4",
      it: "montagna-rocciosa-marrone-sotto-la-notte-stellata-78B_asQgBJ4",
      ko: "별이-빛나는-밤-아래-갈색-록키-산-78B_asQgBJ4",
      de: "brauner-rocky-mountain-unter-sternenklarer-nacht-78B_asQgBJ4",
      pt: "montanha-rochosa-marrom-sob-a-noite-estrelada-78B_asQgBJ4",
    },
    created_at: "2021-06-26T16:33:33Z",
    updated_at: "2024-08-26T20:46:20Z",
    promoted_at: "2021-06-27T04:36:15Z",
    width: 5304,
    height: 7952,
    color: "#0c2626",
    blur_hash: "L46RM%_19aE30hE3sSxD4nMy-.%K",
    description: null,
    alt_description: "brown rocky mountain under starry night",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1624724587078-df79f0084930?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1624724587078-df79f0084930?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1624724587078-df79f0084930?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1624724587078-df79f0084930?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1624724587078-df79f0084930?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1624724587078-df79f0084930",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-rocky-mountain-under-starry-night-78B_asQgBJ4",
      html: "https://unsplash.com/photos/brown-rocky-mountain-under-starry-night-78B_asQgBJ4",
      download:
        "https://unsplash.com/photos/78B_asQgBJ4/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/78B_asQgBJ4/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 270,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2021-06-28T11:17:22Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "1F0CLdMcH2U",
      updated_at: "2023-12-24T15:38:54Z",
      username: "lazyeyedone",
      name: "Tesson Thaliath",
      first_name: "Tesson",
      last_name: "Thaliath",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "Dubai, United Arab Emirates",
      links: {
        self: "https://api.unsplash.com/users/lazyeyedone",
        html: "https://unsplash.com/@lazyeyedone",
        photos: "https://api.unsplash.com/users/lazyeyedone/photos",
        likes: "https://api.unsplash.com/users/lazyeyedone/likes",
        portfolio: "https://api.unsplash.com/users/lazyeyedone/portfolio",
        following: "https://api.unsplash.com/users/lazyeyedone/following",
        followers: "https://api.unsplash.com/users/lazyeyedone/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1624724329137-92e6585bf3a1image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1624724329137-92e6585bf3a1image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1624724329137-92e6585bf3a1image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "lazyeyedone",
      total_collections: 0,
      total_likes: 0,
      total_photos: 205,
      total_promoted_photos: 24,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "lazyeyedone",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7RM2",
      name: "SONY, ILCE-7RM2",
      exposure_time: "15",
      aperture: null,
      focal_length: null,
      iso: 2500,
    },
    location: {
      name: "Wadi Ghalilah - Ras al Khaimah - United Arab Emirates",
      city: null,
      country: "United Arab Emirates",
      position: {
        latitude: 25.962312,
        longitude: 56.100802,
      },
    },
    views: 12327747,
    downloads: 42982,
  },
  {
    id: "FjjHYPUMIyQ",
    slug: "a-very-tall-building-with-a-clock-on-its-side-FjjHYPUMIyQ",
    alternative_slugs: {
      en: "a-very-tall-building-with-a-clock-on-its-side-FjjHYPUMIyQ",
      es: "un-edificio-muy-alto-con-un-reloj-en-su-lado-FjjHYPUMIyQ",
      ja: "横に時計がある非常に高い建物-FjjHYPUMIyQ",
      fr: "un-tres-grand-batiment-avec-une-horloge-sur-le-cote-FjjHYPUMIyQ",
      it: "un-edificio-molto-alto-con-un-orologio-sul-lato-FjjHYPUMIyQ",
      ko: "측면에-시계가있는-매우-높은-건물-FjjHYPUMIyQ",
      de: "ein-sehr-hohes-gebaude-mit-einer-uhr-an-der-seite-FjjHYPUMIyQ",
      pt: "um-edificio-muito-alto-com-um-relogio-ao-seu-lado-FjjHYPUMIyQ",
    },
    created_at: "2023-04-07T19:25:41Z",
    updated_at: "2024-08-26T21:04:17Z",
    promoted_at: "2023-04-08T08:19:40Z",
    width: 5184,
    height: 7752,
    color: "#598c8c",
    blur_hash: "L7CQPeu4Sg%L3Wt-xuRPK*IoDjni",
    description: "Super balconies",
    alt_description: "a very tall building with a clock on it's side",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1680894286281-350d45ca0406?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1680894286281-350d45ca0406?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1680894286281-350d45ca0406?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1680894286281-350d45ca0406?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1680894286281-350d45ca0406?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1680894286281-350d45ca0406",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-very-tall-building-with-a-clock-on-its-side-FjjHYPUMIyQ",
      html: "https://unsplash.com/photos/a-very-tall-building-with-a-clock-on-its-side-FjjHYPUMIyQ",
      download:
        "https://unsplash.com/photos/FjjHYPUMIyQ/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/FjjHYPUMIyQ/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 87,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "ZHQJY8GfnhE",
      updated_at: "2024-05-30T06:56:11Z",
      username: "jakee5000",
      name: "Jake Noble",
      first_name: "Jake",
      last_name: "Noble",
      twitter_username: "jakenobleuk",
      portfolio_url: "http://jakenoble.co.uk",
      bio: null,
      location: "Brighton & Hove",
      links: {
        self: "https://api.unsplash.com/users/jakee5000",
        html: "https://unsplash.com/@jakee5000",
        photos: "https://api.unsplash.com/users/jakee5000/photos",
        likes: "https://api.unsplash.com/users/jakee5000/likes",
        portfolio: "https://api.unsplash.com/users/jakee5000/portfolio",
        following: "https://api.unsplash.com/users/jakee5000/following",
        followers: "https://api.unsplash.com/users/jakee5000/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1641147665-920305574003.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1641147665-920305574003.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1641147665-920305574003.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "jakenobleuk",
      total_collections: 0,
      total_likes: 13,
      total_photos: 85,
      total_promoted_photos: 13,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "jakenobleuk",
        portfolio_url: "http://jakenoble.co.uk",
        twitter_username: "jakenobleuk",
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "X-T5",
      name: "FUJIFILM, X-T5",
      exposure_time: "1/80",
      aperture: "8.0",
      focal_length: "26.0",
      iso: 400,
    },
    location: {
      name: "Worthing, Worthing, United Kingdom",
      city: "Worthing",
      country: "United Kingdom",
      position: {
        latitude: 50.8147691,
        longitude: -0.3714291,
      },
    },
    views: 2551950,
    downloads: 16116,
  },
  {
    id: "eqt8gFwo5C8",
    slug: "body-of-water-and-pine-trees-eqt8gFwo5C8",
    alternative_slugs: {
      en: "body-of-water-and-pine-trees-eqt8gFwo5C8",
      es: "cuerpo-de-agua-y-pinos-eqt8gFwo5C8",
      ja: "水域と松の木-eqt8gFwo5C8",
      fr: "plan-deau-et-pins-eqt8gFwo5C8",
      it: "specchio-dacqua-e-pini-eqt8gFwo5C8",
      ko: "수역과-소나무-eqt8gFwo5C8",
      de: "gewasser-und-kiefern-eqt8gFwo5C8",
      pt: "corpo-de-agua-e-pinheiros-eqt8gFwo5C8",
    },
    created_at: "2019-11-12T09:30:37Z",
    updated_at: "2024-08-26T20:25:41Z",
    promoted_at: "2019-11-12T16:12:52Z",
    width: 3840,
    height: 5672,
    color: "#f3f3f3",
    blur_hash: "L,Hx?7V@IUof~qWVRjay%Mj[t7WB",
    description: null,
    alt_description: "body of water and pine trees",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1573551013875-a54c2a879deb?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1573551013875-a54c2a879deb?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1573551013875-a54c2a879deb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1573551013875-a54c2a879deb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1573551013875-a54c2a879deb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1573551013875-a54c2a879deb",
    },
    links: {
      self: "https://api.unsplash.com/photos/body-of-water-and-pine-trees-eqt8gFwo5C8",
      html: "https://unsplash.com/photos/body-of-water-and-pine-trees-eqt8gFwo5C8",
      download:
        "https://unsplash.com/photos/eqt8gFwo5C8/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/eqt8gFwo5C8/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 470,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-04-06T14:20:12Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "XZDJrfKzdWY",
      updated_at: "2024-09-16T15:44:13Z",
      username: "eberhardgross",
      name: "eberhard 🖐 grossgasteiger",
      first_name: "eberhard 🖐",
      last_name: "grossgasteiger",
      twitter_username: null,
      portfolio_url: "https://narrateography.art",
      bio: "Photography is so incredibly complex, although seemingly simplistic.",
      location: "South Tyrol, Italy",
      links: {
        self: "https://api.unsplash.com/users/eberhardgross",
        html: "https://unsplash.com/@eberhardgross",
        photos: "https://api.unsplash.com/users/eberhardgross/photos",
        likes: "https://api.unsplash.com/users/eberhardgross/likes",
        portfolio: "https://api.unsplash.com/users/eberhardgross/portfolio",
        following: "https://api.unsplash.com/users/eberhardgross/following",
        followers: "https://api.unsplash.com/users/eberhardgross/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "eberhard_grossgasteiger",
      total_collections: 6,
      total_likes: 4796,
      total_photos: 2030,
      total_promoted_photos: 1814,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "eberhard_grossgasteiger",
        portfolio_url: "https://narrateography.art",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark III",
      name: "Canon, EOS 5D Mark III",
      exposure_time: "1/90",
      aperture: "4.0",
      focal_length: "70.0",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 14386509,
    downloads: 18104,
  },
  {
    id: "ID48ekBTlDo",
    slug: "black-and-white-eagle-flying-ID48ekBTlDo",
    alternative_slugs: {
      en: "black-and-white-eagle-flying-ID48ekBTlDo",
      es: "aguila-blanca-y-negra-volando-ID48ekBTlDo",
      ja: "黒と白の鷲が飛ぶ-ID48ekBTlDo",
      fr: "aigle-noir-et-blanc-volant-ID48ekBTlDo",
      it: "aquila-in-bianco-e-nero-che-vola-ID48ekBTlDo",
      ko: "흑인과-백인-독수리-비행-ID48ekBTlDo",
      de: "schwarz-weisser-adler-fliegen-ID48ekBTlDo",
      pt: "aguia-preta-e-branca-voando-ID48ekBTlDo",
    },
    created_at: "2021-01-26T19:30:49Z",
    updated_at: "2024-09-15T18:49:28Z",
    promoted_at: "2021-01-26T20:06:02Z",
    width: 5402,
    height: 7203,
    color: "#0c2626",
    blur_hash: "LiCsz1%MWBof~qxuWCof?bs:ayj[",
    description: null,
    alt_description: "black and white eagle flying",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1611689342806-0863700ce1e4",
    },
    links: {
      self: "https://api.unsplash.com/photos/black-and-white-eagle-flying-ID48ekBTlDo",
      html: "https://unsplash.com/photos/black-and-white-eagle-flying-ID48ekBTlDo",
      download:
        "https://unsplash.com/photos/ID48ekBTlDo/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/ID48ekBTlDo/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 2245,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2021-10-03T16:56:45Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2021-02-22T11:54:58Z",
      },
      animals: {
        status: "approved",
        approved_on: "2021-01-27T11:24:02Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "w2UxSnKeSuc",
      updated_at: "2024-09-12T15:27:53Z",
      username: "buchstabenhausen",
      name: "Philipp Pilz",
      first_name: "Philipp",
      last_name: "Pilz",
      twitter_username: null,
      portfolio_url: null,
      bio: "designer & photographer ↟ german based ↟ capturing atmospheric nature within moody tones  ↟ www.buchstabenhausen.de",
      location: "Bielefeld, Germany",
      links: {
        self: "https://api.unsplash.com/users/buchstabenhausen",
        html: "https://unsplash.com/@buchstabenhausen",
        photos: "https://api.unsplash.com/users/buchstabenhausen/photos",
        likes: "https://api.unsplash.com/users/buchstabenhausen/likes",
        portfolio: "https://api.unsplash.com/users/buchstabenhausen/portfolio",
        following: "https://api.unsplash.com/users/buchstabenhausen/following",
        followers: "https://api.unsplash.com/users/buchstabenhausen/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1611689283666-173278c4384eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1611689283666-173278c4384eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1611689283666-173278c4384eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "buchstabenhausen",
      total_collections: 0,
      total_likes: 4,
      total_photos: 15,
      total_promoted_photos: 15,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "buchstabenhausen",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 6D Mark II",
      name: "Canon, EOS 6D Mark II",
      exposure_time: "1/2000",
      aperture: "4.0",
      focal_length: "300.0",
      iso: 1250,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 10557973,
    downloads: 141064,
  },
  {
    id: "qARGb5J1_yM",
    slug: "a-view-of-a-valley-with-a-village-in-the-distance-qARGb5J1_yM",
    alternative_slugs: {
      en: "a-view-of-a-valley-with-a-village-in-the-distance-qARGb5J1_yM",
      es: "una-vista-de-un-valle-con-un-pueblo-en-la-distancia-qARGb5J1_yM",
      ja: "遠くに村がある谷の眺め-qARGb5J1_yM",
      fr: "une-vue-dune-vallee-avec-un-village-au-loin-qARGb5J1_yM",
      it: "una-vista-di-una-valle-con-un-villaggio-in-lontananza-qARGb5J1_yM",
      ko: "멀리-마을이-있는-계곡의-전망-qARGb5J1_yM",
      de: "blick-auf-ein-tal-mit-einem-dorf-in-der-ferne-qARGb5J1_yM",
      pt: "uma-vista-de-um-vale-com-uma-aldeia-a-distancia-qARGb5J1_yM",
    },
    created_at: "2022-05-22T10:58:36Z",
    updated_at: "2024-08-26T20:56:05Z",
    promoted_at: "2022-05-22T18:08:01Z",
    width: 6000,
    height: 4000,
    color: "#26260c",
    blur_hash: "LTDS,Vo#RlkD?wxaNHj]tUNIoIs.",
    description: null,
    alt_description: "a view of a valley with a village in the distance",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "stock",
        title: "Stock Photos & Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cover",
        title: "Cover Photos & Images",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1653216977227-fa2ae9547f96?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1653216977227-fa2ae9547f96?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1653216977227-fa2ae9547f96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1653216977227-fa2ae9547f96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1653216977227-fa2ae9547f96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1653216977227-fa2ae9547f96",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-view-of-a-valley-with-a-village-in-the-distance-qARGb5J1_yM",
      html: "https://unsplash.com/photos/a-view-of-a-valley-with-a-village-in-the-distance-qARGb5J1_yM",
      download:
        "https://unsplash.com/photos/qARGb5J1_yM/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/qARGb5J1_yM/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 202,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "rejected",
      },
    },
    asset_type: "photo",
    user: {
      id: "NS9FujfPw5A",
      updated_at: "2024-09-13T15:02:35Z",
      username: "idbronskiy",
      name: "Ilia Bronskiy",
      first_name: "Ilia",
      last_name: "Bronskiy",
      twitter_username: "IDBronskiy",
      portfolio_url: null,
      bio: "Discover Switzerland with me 🇨🇭\r\nPhotographer, Content Creator",
      location: "Zurich, Switzerland",
      links: {
        self: "https://api.unsplash.com/users/idbronskiy",
        html: "https://unsplash.com/@idbronskiy",
        photos: "https://api.unsplash.com/users/idbronskiy/photos",
        likes: "https://api.unsplash.com/users/idbronskiy/likes",
        portfolio: "https://api.unsplash.com/users/idbronskiy/portfolio",
        following: "https://api.unsplash.com/users/idbronskiy/following",
        followers: "https://api.unsplash.com/users/idbronskiy/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1697231135988-15896ef5f3d6?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1697231135988-15896ef5f3d6?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1697231135988-15896ef5f3d6?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "idbronskiy",
      total_collections: 45,
      total_likes: 46,
      total_photos: 922,
      total_promoted_photos: 125,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "idbronskiy",
        portfolio_url: null,
        twitter_username: "IDBronskiy",
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7M3",
      name: "SONY, ILCE-7M3",
      exposure_time: "1/800",
      aperture: "7.1",
      focal_length: "70.0",
      iso: 320,
    },
    location: {
      name: "Weissbad, Switzerland",
      city: "Weissbad",
      country: "Switzerland",
      position: {
        latitude: 47.310552,
        longitude: 9.435555,
      },
    },
    views: 9958123,
    downloads: 67443,
  },
  {
    id: "nM3pjXMoKqo",
    slug: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
    alternative_slugs: {
      en: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      es: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      ja: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      fr: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      it: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      ko: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      de: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      pt: "silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
    },
    created_at: "2018-04-09T16:47:02Z",
    updated_at: "2024-09-16T09:08:34Z",
    promoted_at: "2018-04-10T11:46:02Z",
    width: 7680,
    height: 4800,
    color: "#f3c073",
    blur_hash: "L]OxBNa|RnoL~8jtjGazEhjbW.WW",
    description: "End of Days",
    alt_description: "silhouette of mountains during golden hour",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1523291156648-f729ceff89b9?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1523291156648-f729ceff89b9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1523291156648-f729ceff89b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1523291156648-f729ceff89b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1523291156648-f729ceff89b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1523291156648-f729ceff89b9",
    },
    links: {
      self: "https://api.unsplash.com/photos/silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      html: "https://unsplash.com/photos/silhouette-of-mountains-during-golden-hour-nM3pjXMoKqo",
      download:
        "https://unsplash.com/photos/nM3pjXMoKqo/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/nM3pjXMoKqo/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 164,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "ly3ZTBnZLKY",
      updated_at: "2024-03-13T01:18:05Z",
      username: "imsogabriel",
      name: "imso gabriel",
      first_name: "imso",
      last_name: "gabriel",
      twitter_username: null,
      portfolio_url: "https://linktr.ee/imsogabriel",
      bio: "Photographer and Retoucher\r\nfb @imsogabriel.studios",
      location: "Nairobi, Kenya",
      links: {
        self: "https://api.unsplash.com/users/imsogabriel",
        html: "https://unsplash.com/@imsogabriel",
        photos: "https://api.unsplash.com/users/imsogabriel/photos",
        likes: "https://api.unsplash.com/users/imsogabriel/likes",
        portfolio: "https://api.unsplash.com/users/imsogabriel/portfolio",
        following: "https://api.unsplash.com/users/imsogabriel/following",
        followers: "https://api.unsplash.com/users/imsogabriel/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1666254010268-1983b3c1811aimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1666254010268-1983b3c1811aimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1666254010268-1983b3c1811aimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "imsogabriel_stock",
      total_collections: 2,
      total_likes: 210,
      total_photos: 192,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "imsogabriel_stock",
        portfolio_url: "https://linktr.ee/imsogabriel",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D3200",
      name: "NIKON CORPORATION, NIKON D3200",
      exposure_time: "1/200",
      aperture: "8.0",
      focal_length: "55.0",
      iso: 100,
    },
    location: {
      name: "Nairobi, Kenya",
      city: "Nairobi",
      country: "Kenya",
      position: {
        latitude: -1.2920659,
        longitude: 36.8219462,
      },
    },
    views: 7169688,
    downloads: 7443,
  },
  {
    id: "6GD2iCgeYpA",
    slug: "shallow-focus-photo-of-brown-fox-6GD2iCgeYpA",
    alternative_slugs: {
      en: "shallow-focus-photo-of-brown-fox-6GD2iCgeYpA",
      es: "foto-de-enfoque-superficial-de-zorro-marron-6GD2iCgeYpA",
      ja: "ブラウンフォックスの浅い焦点の写真-6GD2iCgeYpA",
      fr: "photo-de-mise-au-point-peu-profonde-de-renard-brun-6GD2iCgeYpA",
      it: "foto-di-messa-a-fuoco-superficiale-di-volpe-marrone-6GD2iCgeYpA",
      ko: "갈색-여우의-얕은-초점-사진-6GD2iCgeYpA",
      de: "foto-mit-flachem-fokus-von-braunem-fuchs-6GD2iCgeYpA",
      pt: "foto-de-foco-raso-da-raposa-marrom-6GD2iCgeYpA",
    },
    created_at: "2017-08-24T04:47:07Z",
    updated_at: "2024-09-07T23:59:12Z",
    promoted_at: "2017-08-25T08:38:41Z",
    width: 5258,
    height: 3510,
    color: "#597340",
    blur_hash: "L5Cjgmx@ATw4.h-.-VEe58RQ,:xt",
    description: null,
    alt_description: "shallow focus photo of brown fox",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1503550012877-0b1cde05feb5?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1503550012877-0b1cde05feb5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1503550012877-0b1cde05feb5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1503550012877-0b1cde05feb5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1503550012877-0b1cde05feb5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1503550012877-0b1cde05feb5",
    },
    links: {
      self: "https://api.unsplash.com/photos/shallow-focus-photo-of-brown-fox-6GD2iCgeYpA",
      html: "https://unsplash.com/photos/shallow-focus-photo-of-brown-fox-6GD2iCgeYpA",
      download:
        "https://unsplash.com/photos/6GD2iCgeYpA/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/6GD2iCgeYpA/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 944,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "UT41ainZxFI",
      updated_at: "2024-09-11T01:19:07Z",
      username: "nathananderson",
      name: "Nathan Anderson",
      first_name: "Nathan",
      last_name: "Anderson",
      twitter_username: "nathanworking",
      portfolio_url: "https://kunack.us/follow?source=unsplash",
      bio: "Prints now available at Kunack.us",
      location: "Knoxville, TN",
      links: {
        self: "https://api.unsplash.com/users/nathananderson",
        html: "https://unsplash.com/@nathananderson",
        photos: "https://api.unsplash.com/users/nathananderson/photos",
        likes: "https://api.unsplash.com/users/nathananderson/likes",
        portfolio: "https://api.unsplash.com/users/nathananderson/portfolio",
        following: "https://api.unsplash.com/users/nathananderson/following",
        followers: "https://api.unsplash.com/users/nathananderson/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1676320214445-e3fec6f7b87cimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1676320214445-e3fec6f7b87cimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1676320214445-e3fec6f7b87cimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "kunack.us",
      total_collections: 9,
      total_likes: 1224,
      total_photos: 1354,
      total_promoted_photos: 434,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "kunack.us",
        portfolio_url: "https://kunack.us/follow?source=unsplash",
        twitter_username: "nathanworking",
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D750",
      name: "NIKON CORPORATION, NIKON D750",
      exposure_time: "1/250",
      aperture: "7.1",
      focal_length: "390.0",
      iso: 800,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 11371992,
    downloads: 19880,
  },
  {
    id: "1-lYRLuabu4",
    slug: "aerial-photo-of-lake-during-sunset-1-lYRLuabu4",
    alternative_slugs: {
      en: "aerial-photo-of-lake-during-sunset-1-lYRLuabu4",
      es: "foto-aerea-del-lago-durante-la-puesta-del-sol-1-lYRLuabu4",
      ja: "日没時の湖の航空写真-1-lYRLuabu4",
      fr: "photo-aerienne-du-lac-au-coucher-du-soleil-1-lYRLuabu4",
      it: "foto-aerea-del-lago-durante-il-tramonto-1-lYRLuabu4",
      ko: "일몰-중-호수의-항공-사진-1-lYRLuabu4",
      de: "luftaufnahme-des-sees-bei-sonnenuntergang-1-lYRLuabu4",
      pt: "foto-aerea-do-lago-durante-o-por-do-sol-1-lYRLuabu4",
    },
    created_at: "2018-05-23T15:47:46Z",
    updated_at: "2024-08-26T20:09:40Z",
    promoted_at: "2018-05-24T13:09:15Z",
    width: 6720,
    height: 4480,
    color: "#0c2626",
    blur_hash: "LdDvWoo#ELjt~Xj]NwkCXnWAs:j]",
    description:
      "A quick trip up Pen Y Pass this week (May 2018) to catch a perfectly aligned sunset. 🙌🌅",
    alt_description: "aerial photo of lake during sunset",
    breadcrumbs: [
      {
        slug: "backgrounds",
        title: "HQ Background Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Backgrounds",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "landscape",
        title: "Landscape Backgrounds",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1527090296392-920158c27e56?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1527090296392-920158c27e56?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1527090296392-920158c27e56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1527090296392-920158c27e56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1527090296392-920158c27e56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1527090296392-920158c27e56",
    },
    links: {
      self: "https://api.unsplash.com/photos/aerial-photo-of-lake-during-sunset-1-lYRLuabu4",
      html: "https://unsplash.com/photos/aerial-photo-of-lake-during-sunset-1-lYRLuabu4",
      download:
        "https://unsplash.com/photos/1-lYRLuabu4/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/1-lYRLuabu4/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 330,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "5qfGesbkIm0",
      updated_at: "2024-09-12T08:23:55Z",
      username: "neilthomas",
      name: "Neil Mark Thomas",
      first_name: "Neil",
      last_name: "Mark Thomas",
      twitter_username: "neilthomas",
      portfolio_url: "https://www.instagram.com/neilthomas",
      bio: "Astro 🌌 Landscapes 🏞 Cymraeg 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Canon & Sony 📷",
      location: "Wales, UK",
      links: {
        self: "https://api.unsplash.com/users/neilthomas",
        html: "https://unsplash.com/@neilthomas",
        photos: "https://api.unsplash.com/users/neilthomas/photos",
        likes: "https://api.unsplash.com/users/neilthomas/likes",
        portfolio: "https://api.unsplash.com/users/neilthomas/portfolio",
        following: "https://api.unsplash.com/users/neilthomas/following",
        followers: "https://api.unsplash.com/users/neilthomas/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1592490989893-8d317c7dcfa2image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1592490989893-8d317c7dcfa2image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1592490989893-8d317c7dcfa2image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "neilthomas",
      total_collections: 0,
      total_likes: 22,
      total_photos: 68,
      total_promoted_photos: 36,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "neilthomas",
        portfolio_url: "https://www.instagram.com/neilthomas",
        twitter_username: "neilthomas",
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: "Snowdon, Caernarfon, United Kingdom",
      city: "Caernarfon",
      country: "United Kingdom",
      position: {
        latitude: 53.0784047249614,
        longitude: -4.03198796474612,
      },
    },
    views: 7046120,
    downloads: 10884,
  },
  {
    id: "uGHqZRCEWag",
    slug: "a-mountain-with-clouds-in-the-sky-uGHqZRCEWag",
    alternative_slugs: {
      en: "a-mountain-with-clouds-in-the-sky-uGHqZRCEWag",
      es: "una-montana-con-nubes-en-el-cielo-uGHqZRCEWag",
      ja: "空に雲のある山-uGHqZRCEWag",
      fr: "une-montagne-avec-des-nuages-dans-le-ciel-uGHqZRCEWag",
      it: "una-montagna-con-le-nuvole-nel-cielo-uGHqZRCEWag",
      ko: "하늘에-구름이있는-산-uGHqZRCEWag",
      de: "ein-berg-mit-wolken-am-himmel-uGHqZRCEWag",
      pt: "uma-montanha-com-nuvens-no-ceu-uGHqZRCEWag",
    },
    created_at: "2022-11-28T18:47:05Z",
    updated_at: "2024-09-07T23:59:33Z",
    promoted_at: "2022-11-29T20:40:02Z",
    width: 5691,
    height: 3783,
    color: "#264059",
    blur_hash: "LH97eQxaRjWYyEbHf5j]0fNGs:of",
    description: "Lenticular sunrise, Torres del Paine",
    alt_description: "a mountain with clouds in the sky",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1669661007953-33861e3bd46e?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1669661007953-33861e3bd46e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1669661007953-33861e3bd46e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1669661007953-33861e3bd46e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1669661007953-33861e3bd46e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1669661007953-33861e3bd46e",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-mountain-with-clouds-in-the-sky-uGHqZRCEWag",
      html: "https://unsplash.com/photos/a-mountain-with-clouds-in-the-sky-uGHqZRCEWag",
      download:
        "https://unsplash.com/photos/uGHqZRCEWag/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
      download_location:
        "https://api.unsplash.com/photos/uGHqZRCEWag/download?ixid=M3w2NTQzODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjY1MDQzNDZ8",
    },
    likes: 317,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2022-12-03T19:31:31Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "9PgyHObnDOE",
      updated_at: "2024-08-29T19:55:44Z",
      username: "cyrus_smith",
      name: "Marc Thunis",
      first_name: "Marc",
      last_name: "Thunis",
      twitter_username: null,
      portfolio_url: "https://www.flickr.com/photos/137175244@N02/",
      bio: "Thank you for visiting my gallery.\r\nI'm trying to catch and share magical moments.  North and west are my favorite directions...",
      location: "Belgium",
      links: {
        self: "https://api.unsplash.com/users/cyrus_smith",
        html: "https://unsplash.com/@cyrus_smith",
        photos: "https://api.unsplash.com/users/cyrus_smith/photos",
        likes: "https://api.unsplash.com/users/cyrus_smith/likes",
        portfolio: "https://api.unsplash.com/users/cyrus_smith/portfolio",
        following: "https://api.unsplash.com/users/cyrus_smith/following",
        followers: "https://api.unsplash.com/users/cyrus_smith/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1584262592389-9a3dcb108ec8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1584262592389-9a3dcb108ec8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1584262592389-9a3dcb108ec8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 35,
      total_photos: 39,
      total_promoted_photos: 9,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: "https://www.flickr.com/photos/137175244@N02/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D5500",
      name: "NIKON CORPORATION, NIKON D5500",
      exposure_time: "1/50",
      aperture: "4.8",
      focal_length: "36.0",
      iso: 100,
    },
    location: {
      name: "Torres del Paine, Torres de Paine, Chile",
      city: "Torres del Paine",
      country: "Chile",
      position: {
        latitude: -51.253257,
        longitude: -72.351677,
      },
    },
    views: 5511123,
    downloads: 20346,
  },
];
